version: '3.7'

services:
  ui:
    image: node:13.12.0-alpine
    working_dir: /app
    volumes:
      - ./client:/app
    command: npm start
    ports:
      - 3000:3000
    links:
      - server
    stdin_open: true

  server:
    image: node:13.12.0-alpine
    working_dir: /app
    volumes:
      - ./server:/app
    command: npm start
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8080:8080